### ISSUE TITLE
Improve memory protection in multi stage query engine

### ISSUE THREAD

**Issue by gortiz** [apache/pinot#13436]
This is a meta-issue to track memory protection mechanism in multi-stage. Specifically, the following mechanisms are included in single-stage query engine but are not present in multi-stage:

- OOM protection (killing heavy allocating queries when getting out of heap memory, see #13433)
- Default limits (add a default limit if no limit is included, see #13434)
- Approximate grouping algorithm (see #13435)

**Comment by hpvd** [comment]
I like this kind of parent issues :-)

Just an idea: if we use syntax like this, we get a nice tasklist with checkboxes and can see the progress without even opening the issue
```
- [ ] OOM protection (killing heavy allocating queries when getting out of heap memory, see #13433
- [ ] Default limits (add a default limit if no limit is included, see #13434
- [ ] Approximate grouping algorithm, see #13435
```

Maybe someone could ad a label "Parent-Issue" we could even filter for them...

inspired by https://github.com/apache/pinot/issues/13010

**Comment by gortiz** [comment]
I thought about using that syntax, but looks repetitive. Once the referenced issue is closed, it will be shown as purple instead of green (like it is right now).

**Comment by hpvd** [comment]
yeap understand. thanks for changes.
Just fyi since I'm lazy: you only have to input the first point plus issue number, after that every return starts a new point...

```

- [ ] #13433
- [ ]  

```
