### ISSUE TITLE
[Tracker] Generic Time Series Engine in Pinot

### ISSUE THREAD

**Issue by ankitsultana** [apache/pinot#13957]
Tracker for the proposal in #13760.

### Milestones

- [x] Add SPI code to main
- [x] Add E2E single server support to main
- [ ] Robust Phase-1 implementation, and mark Phase-1 as closed.
- [ ] Add support for Instant Vectors

### Misc. Tasks

- [x] Fix naming convention of series
- [ ] Rename aggInfo
- [x] Fix offset calculation (honor time unit)
- [x] Share example of implementing a function like rate
- [x] Rename ScanFilterAndProjectPlanNode
- [x] Support groupByExpressions and not just columns.
- [ ] Add metrics for monitoring
- [ ] Error categorization
- [ ] Add support for default time columns
- [x] Change Time Series Logical Planner to take in PinotConfiguration instead of a Map.
- [ ] Add support for configuring broker response
