### ISSUE TITLE
Enforce maven codestyle check during maven build

### ISSUE THREAD

**Issue by xiangfu0** [apache/pinot#7309]
Enforce maven codestyle check during maven builds, currently we set violation severity to warning and suppress errors right now.

- [x] Adding checks at root pom, then we can fix each component
- Fix coding style for all components：
    - [x] pinot-adls #7314 
    - [x] pinot-avro-base #7314 
    - [x] pinot-avro #7314 
    - [x] pinot-azure #7314 
    - [x] pinot-batch-ingestion-common #7314 
    - [x] pinot-batch-ingestion-hadoop #7314 
    - [x] pinot-batch-ingestion-spark #7314 
    - [x] pinot-batch-ingestion-standalone #7314 
    - [x] pinot-broker #7333
    - [x] pinot-clients #7326 
    - [x] pinot-common #7311 
    - [x] pinot-confluent-avro #7314 
    - [x] pinot-controller #7331
    - [ ] pinot-core #7325 
    - [x] pinot-csv #7314 
    - [x] pinot-dropwizard #7314 
    - [x] pinot-gcs #7314 
    - [x] pinot-hadoop #7314 
    - [x] pinot-hdfs #7314 
    - [x] pinot-ingestion-common #7314 
    - [ ] pinot-integration-tests #7335 
    - [x] pinot-java-client #7326 
    - [x] pinot-jdbc-client #7326 
    - [x] pinot-json #7314 
    - [x] pinot-kafka-0.9 #7314 
    - [x] pinot-kafka-2.0 #7314 
    - [x] pinot-kafka-base #7314 
    - [x] pinot-kinesis #7314 
    - [x] pinot-minion-builtin-tasks #7314 
    - [ ] pinot-minion #7335 
    - [x] pinot-orc #7314 
    - [x] pinot-parquet #7314 
    - [ ] pinot-perf #7335 
    - [x] pinot-protobuf #7314 
    - [x] pinot-pulsar #7314 
    - [x] pinot-s3 #7314 
    - [x] pinot-segment-local #7317 
    - [x] pinot-segment-spi #7317 
    - [x] pinot-segment-uploader-default #7314 
    - [x] pinot-segment-uploader #7314 
    - [x] pinot-segment-writer-file-based #7314 
    - [x] pinot-segment-writer #7314 
    - [x] pinot-server #7334 
    - [ ] pinot-spark-connector #7335 
    - [x] pinot-spark #7314 
    - [x] pinot-spi #7308 
    - [x] pinot-thrift #7314 
    - [ ] pinot-tools #7335 
    - [x] pinot-yammer #7314

**Comment by xiangfu0** [comment]
All the reformat is done.
And enabled codestyle check for all java components.
